# Generated by Django 3.1.7 on 2021-03-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchtutor', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='searchtutor.tutor')),
            ],
        ),
    ]
