# Generated by Django 3.1.7 on 2021-03-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchtutor', '0004_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.CharField(max_length=30)),
                ('session_time', models.CharField(max_length=30)),
                ('session_duration', models.CharField(max_length=30)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='searchtutor.bill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='searchtutor.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='searchtutor.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='searchtutor.tutor')),
            ],
        ),
    ]
